### ISSUE TITLE
[ziwooda] add Namespace in Deployment

### ISSUE THREAD

**Issue by ziwooda** [JUJY-OIDC/etcd-autobackup#91]
add namespace config. in Deloyment files
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-watchapi-deploy
  namespace: etcd-autobackup
  ...
```

⇢ not need to add `-n etcd-autobackup` via cli command
